### ISSUE TITLE
Use overflow:scroll for syntax highlighted code

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/bin.cakephp.org#2]
This would allow code to be as long as necessary.

Please note that this would potentially require some markup changes as just setting this style also sets the background color of the overflow to the same as the line numbers.

Example where this is an issue:

http://bin.cakephp.org/saved/79042

![http://cl.ly/image/3b3i3O302A2f](http://f.cl.ly/items/2G142j2Q110y1L0q0J15/Screen%20Shot%202012-10-17%20at%2010.59.16%20AM.png)

**Comment by markstory** [comment]
I think that makes sense, adding `overflow-x: auto` to the containing div seems to get 80% of the way there.

**Comment by markstory** [comment]
This should be fixed as of 22211070094a46d919a67927bf55f9aa9e85f4a4

**Comment by renan** [comment]
The problem now is that line number doesn't match anymore.

`this line` gets moved to next time, on line number 6 when it should be still line number 5.

**Comment by markstory** [comment]
@renansaddam Where is that happening?

**Comment by renan** [comment]
It was happening in the bin above (http://bin.cakephp.org/saved/79042), but now seems fixed. :)

**Comment by markstory** [comment]
Interesting, I didn't modify the code in between it breaking and being fixed.  I wonder what changed.
