### ISSUE TITLE
Searching Tells Function

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/bin.cakephp.org#3]
Searching on the tells page searches logs, not the tells.

Refs cakephp/cakebot#4

**Comment by markstory** [comment]
The bin has a tells page?

**Comment by josegonzalez** [comment]
Do ~tells in irc!

**Comment by dereuromark** [comment]
Actually, the original issue https://github.com/cakephp/cakebot/issues/4 was the right place.
There is all the web CRUD for the tells.
This repo here contains sth else.
